apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    name: backend-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: zarexalvindaria/backend-tracing:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 5050
      targetPort: 5050
  type: LoadBalancer